{{ config(materialized='incremental') }}

with employee_data as (

    select  "PERSON_ID" :: integer,
            "EMPLOYEE_NUMBER" :: VARCHAR(30),
            "EFFECTIVE_START_DATE" :: DATE,
            "EFFECTIVE_END_DATE" :: DATE,
            "PERSON_TYPE_ID" :: integer,
            "FIRST_NAME" :: VARCHAR(150),
            "MIDDLE_NAMES" :: VARCHAR(60),
            "LAST_NAME" :: VARCHAR(150),
            "FULL_NAME" :: VARCHAR(240),
            "SUP_PERSON_ID" :: integer,
            "SUP_EMPLOYEE_NUMBER" :: VARCHAR(30),
            "SUP_START_DATE" :: DATE,
            "SUP_END_DATE" :: DATE,
            "SUP_PERSON_TYPE_ID" :: integer,
            "SUP_FIRST_NAME" :: VARCHAR(150),
            "SUP_MIDDLE_NAMES" :: VARCHAR(60),
            "SUP_LAST_NAME" :: VARCHAR(150),
            "SUP_FULL_NAME" :: VARCHAR(240),
            "START_DATE" :: DATE,
            "APPLICANT_NUMBER" :: VARCHAR(30),
            "BACKGROUND_CHECK_STATUS" :: VARCHAR(30),
            "BACKGROUND_DATE_CHECK" :: VARCHAR(30),
            "BLOOD_TYPE" :: VARCHAR(30),
            "CORRESPONDENCE_LANGUAGE" :: VARCHAR(30),
            "CURRENT_APPLICANT_FLAG" :: VARCHAR(30),
            "CURRENT_EMP_OR_APL_FLAG" :: VARCHAR(30),
            "CURRENT_EMPLOYEE_FLAG" :: VARCHAR(30),
            "DATE_EMPLOYEE_DATA_VERIFIED" :: VARCHAR(30),
            "EMAIL_ADDRESS" :: VARCHAR(240),
            "MARITAL_STATUS" :: VARCHAR(30),
            "NATIONALITY" :: VARCHAR(30),
            "PREVIOUS_LAST_NAME" :: VARCHAR(150),
            "PROJECTED_START_DATE" :: VARCHAR(30),
            "REHIRE_AUTHORIZOR" :: VARCHAR(30),
            "REHIRE_REASON" :: VARCHAR(60),
            "REHIRE_RECOMMENDATION" :: VARCHAR(30),
            "SEX" :: VARCHAR(30),
            "LAST_UPDATE_DATE" :: VARCHAR(30),
            "LAST_UPDATED_BY" :: integer,
            "CREATION_DATE" :: VARCHAR(30),
            "CREATED_BY" :: integer,
            "OBJECT_VERSION_NUMBER" :: integer,
            "DATE_OF_DEATH" :: VARCHAR(30),
            "ORIGINAL_DATE_OF_HIRE" :: VARCHAR(30),
            "TOWN_OF_BIRTH" :: VARCHAR(90),
            "REGION_OF_BIRTH" :: VARCHAR(90),
            "COUNTRY_OF_BIRTH" :: VARCHAR(90),
            "PARTY_ID" :: integer,
            "GLOBAL_NAME" :: VARCHAR(240),
            "LOCAL_NAME" :: VARCHAR(240),
            "APPROVAL_LIMIT" :: VARCHAR(150),
            "JOB_NAME" :: VARCHAR(700),
            "COST_CENTER" :: VARCHAR(25),
            "BRAND" :: VARCHAR(25),
            "GEO" :: VARCHAR(25),
            "CHANNEL" :: VARCHAR(25),
            "GL_STRING" :: VARCHAR(207),
            "ATTRIBUTE_CATEGORY" :: VARCHAR(30),
            "ATTRIBUTE1" :: VARCHAR(150),
            "ATTRIBUTE2" :: VARCHAR(150),
            "ATTRIBUTE3" :: VARCHAR(150),
            "ATTRIBUTE4" :: VARCHAR(150),
            "ATTRIBUTE5" :: VARCHAR(150),
            "ATTRIBUTE6" :: VARCHAR(150),
            "ATTRIBUTE7" :: VARCHAR(150),
            "ATTRIBUTE8" :: VARCHAR(150),
            "ATTRIBUTE9" :: VARCHAR(150),
            "ATTRIBUTE10" :: VARCHAR(150)

    from {{ source('fivetran_SFTP_source','employee') }}

)

select * from employee_data
