
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: fivetran_SFTP_source
    description: "read from sftp"
    columns:
      - schema: sftp
        description: "read from sftp schema tables employee"
        tables:
          - name: employee
